### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by czy112** [shaoshengsong/MobileNetV3-SSD-Compact-Version#1]
with open(os.path.join(data_folder, self.split + '_objects.json'), 'r') as j:
FileNotFoundError: [Errno 2] No such file or directory: './TRAIN_objects.json'

请问在用自己数据集训练时，需要提前划分出train，val,test的json文件是吗？
还有一些测试问题，不知道您能不能提供邮箱或者qq联系您。
我的q:212587194
谢谢！

**Comment by shaoshengsong** [comment]
如果是自己的数据集 ，推荐先转换成通用的VOC格式，然后打开create_data_lists.py文件 改成自己数据集的路径，再执行create_data_lists.py即可。

**Comment by jideee** [comment]
你好 eval.py 我怎么运行不了
Traceback (most recent call last):
File "eval.py", line 90, in
evaluate(test_loader, model)
File "eval.py", line 65, in evaluate
top_k=200)
File "/home/cjd/MobileNetV3-SSD-Compact-Version-master/model.py", line 463, in detect_objects
suppress = torch.max(suppress, overlap[box] > max_overlap)
RuntimeError: _th_max not supported on CUDAType for Bool

我会出现这种情况 望解答 谢谢
