### ISSUE TITLE
关于学习率设置

### ISSUE THREAD

**Issue by yangyang117** [shaoshengsong/MobileNetV3-SSD-Compact-Version#6]
楼主你好，我想复现你这个0.678的结果，但是采用你代码中现有的设置，发现无法复现。请问lr应该倾向于怎么样的设置呢？

**Comment by jideee** [comment]
你好 请问你能运行 eval.py吗  我怎么运行不了
Traceback (most recent call last):
  File "eval.py", line 90, in <module>
    evaluate(test_loader, model)
  File "eval.py", line 65, in evaluate
    top_k=200)
  File "/home/cjd/MobileNetV3-SSD-Compact-Version-master/model.py", line 463, in detect_objects
    suppress = torch.max(suppress, overlap[box] > max_overlap)
RuntimeError: _th_max not supported on CUDAType for Bool

我会出现这种情况
